FROM node:10 AS webpack-build
# Lighter Node version
# FROM node:current-slim

# Copy directory to container
COPY ./client/package.json ./client/yarn.lock ./client/.npmrc /app/client/

WORKDIR /app/client

RUN id
RUN stat /usr/local/lib/node_modules/npm/bin/npm-cli.js
# Install dependencies
RUN yarn

COPY . /app/

# Set working directory
RUN yarn build


FROM nginx:1.14.0

COPY --from=webpack-build /app/client/build /app

COPY ./nginx-client-config.conf /etc/nginx/conf.d/default.conf 

EXPOSE 80
