version: "3.2"
services:
    client:
        image: client
        build:
            context: .
            dockerfile: Dockerfile-client
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/ssl:/etc/ssl
#        deploy:
#            labels:
#                com.docker.lb.ssl_cert: tokenizer.app.cert
#                com.docker.lb.ssl_key: tokenizer.app.key
        restart: always
        depends_on:
            - server
    server:
        image: server
        env_file:
            - ./env/prod.env
        build:
            context: .
            dockerfile: Dockerfile-server
            #        ports:
            #            - "3030:3030"
        restart: always
    database:
        image: mongo
        volumes:
            - /opt/issuer/db:/data/db
        ports:
            - "27018:27017"
secrets:
    tokenizer.app.cert:
        file: ./app.tokenizer.cert
    tokenizer.app.key:
        file: ./app.tokeninzer.key

networks:
    default:
        external:
            name: tokenizer-network
