FROM node:10
# Lighter Node version
# FROM node:current-slim

# Copy client package.json
COPY package*.json /app/

# Copy directory to container
COPY . /app/

# Set working directory
WORKDIR /app

# Install dependencies
RUN npm install

# Use port 3000
EXPOSE 3000

#RUN ["chmod", "+x", "/usr/local/bin/docker-entrypoint.sh"]

CMD ["npm", "start"]
